 @endpoint = https://blbpcnjx-5001.euw.devtunnels.ms

### Get invitations
GET {{endpoint}}/api/invitation HTTP/1.1
Content-Type: application/json

### Create invitation
POST {{endpoint}}/api/invitation HTTP/1.1
Content-Type: application/json

{
    "email": "admin@contoso.com",
    "invitationCode": "1122334455"
}

### Validate without invitation code
POST {{endpoint}}/api/validation HTTP/1.1
Content-Type: application/json
Authorization: Basic apiconnector:$uperSecr€t1!

{
  "step": "string",
  "objectId": "string",
  "givenName": "string",
  "surname": "string",
  "jobTitle": "string",
  "streetAddress": "string",
  "city": "string",
  "postalCode": "string",
  "state": "string",
  "country": "string",
  "client_id": "string",
  "ui_locales": "string",
  "email": "string",
  "displayName": "string",
  "identities": [
    {
      "signInType": "string",
      "issuer": "string",
      "issuerAssignedId": "string"
    }
  ],
  "additionalProp1": "string",
  "additionalProp2": "string",
  "additionalProp3": "string"
}

### Validate with invitation code
POST {{endpoint}}/api/validation HTTP/1.1
Content-Type: application/json
Authorization: Basic apiconnector:$uperSecr€t1!

{
  "step": "string",
  "objectId": "string",
  "givenName": "string",
  "surname": "string",
  "jobTitle": "string",
  "streetAddress": "string",
  "city": "string",
  "postalCode": "string",
  "state": "string",
  "country": "string",
  "client_id": "string",
  "ui_locales": "string",
  "email": "admin@contoso.com",
  "displayName": "string",
  "identities": [
    {
      "signInType": "string",
      "issuer": "string",
      "issuerAssignedId": "string"
    }
  ],
  "extension_af3257c73cb0499da4b1ef4e0db3be1f_InvitationCode": "1122334455",
  "additionalProp2": "string",
  "additionalProp3": "string"
}

### Get invitations
POST {{endpoint}}/api/ClaimExtender HTTP/1.1
Content-Type: application/json

{
  "userPrincipalName": "5e5a77ac-6a6a-4ed7-8df2-e2792f1da401@<yourtenantname>.onmicrosoft.com",
  "objectId": "5e5a77ac-6a6a-4ed7-8df2-e2792f1da401",
  "givenName": "John",
  "surName": "Smith"
}